### ISSUE TITLE
Authentication fails with error message "PublicKey algorithm cannot be null"

### ISSUE THREAD

**Issue by lhotari** [datastax/pulsar-openid-connect-plugin#9]
### Problem

Authentication fails with error message "PublicKey algorithm cannot be null"

### Explanation

When inspecting the issue, it looks like the issue is in this code:
https://github.com/datastax/pulsar-openid-connect-plugin/blob/9c3aeabc07c087d51d32bb1c494583b5aac5dde2/src/main/java/com/datastax/oss/pulsar/auth/AuthenticationProviderOpenID.java#L270-L283

line 278 `return verifyJWT(jwk.getPublicKey(), jwk.getAlgorithm(), jwt);` takes the algorithm from the wrong object.
It should be `jwt.getAlgorithm()` instead of `jwk.getAlgorithm()`.

**Comment by michaeljmarshall** [comment]
For context, I made the mistake of assuming the JWK would always have the `alg` field. This was incorrect. The JWK spec lists the `alg` field as optional: https://datatracker.ietf.org/doc/html/rfc7517#section-4.4. Instead it should come from the JWT, as you propose: https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.1.
